### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by fungfrankie** [thetorque/pulse_sequencer#3]
I just set up LabRAD and I'm trying to replicate what you have in your paper, but encountered this error while running the Python server pulser_ok.py:

"ImportError: DLL load failed: %1 is not a valid Win32 application."

I'm running Windows 10 64-bit, and I installed FrontPanel 64-bit (4.5.0). I tried installing FrontPanel 32-bit too but that didn't help. I also have pywin32 installed if that matters. 

```
Traceback (most recent call last):
  File "C:/Users/SenkoLab/Documents/GitHub/pulse_sequencer-master/Python_files/servers/pulser/pulser_ok.py", line 28, in <module>
    from api import api
  File "C:\Users\SenkoLab\Documents\GitHub\pulse_sequencer-master\Python_files\servers\pulser\api.py", line 1, in <module>
    import ok
  File "C:\Users\SenkoLab\Documents\GitHub\pulse_sequencer-master\Python_files\servers\pulser\ok.py", line 26, in <module>
    _ok = swig_import_helper()
  File "C:\Users\SenkoLab\Documents\GitHub\pulse_sequencer-master\Python_files\servers\pulser\ok.py", line 22, in swig_import_helper
    _mod = imp.load_module('_ok', fp, pathname, description)
ImportError: DLL load failed: %1 is not a valid Win32 application.

Process finished with exit code 1

```

Thanks!

**Comment by fungfrankie** [comment]
Solved it by downloading the 64-bit Python API files from Opal Kelly:
__init__.py
__version__.py
_ok.pyd
ok.py
I replaced the files in the server folder with the above 4 and now I can run the server.
